version: "3.7"
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: production
