services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      NODE_ENV: development
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
