import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./user/UserContext";
import { TrpcProvider } from "@web/contexts/TrpcContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ult Stack",
  description: "Generated by Ult Stack",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TrpcProvider>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </UserProvider>
    </TrpcProvider>
  );
}
