import PrelineScript from "@web/components/PrelineScript";
import { TrpcProvider } from "@web/contexts/TrpcContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./user/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ult",
  description: "Generated by Ult",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TrpcProvider>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
        <PrelineScript />
      </UserProvider>
    </TrpcProvider>
  );
}
